### ISSUE TITLE
Using scrollbars copies code

### ISSUE THREAD

**Issue by gh3597** [nicolasprigent/Dokuwiki-Copycode-plugin#12]
DokuWiki Version: Release 2023-04-04a "Jack Jackrum"
Copycode Version: 2023-06-14

When the box has a scrollbar then using the scroll bar triggers the copycode plugin, overwriting what I already have in the clipboard.

**Comment by nicolasprigent** [comment]
Hello, ok that's something that I haven't planned when I did the script. I'll implement a fix a soon as possible.

**Comment by nicolasprigent** [comment]
hello @gh3597 , I've just updated the plugin regarding your issue, that was a tricky one :).
I've tested the fix on my dokuwiki installation and it doesn't  click after scroll anymore.
Let me know if it works for ok for you too.

**Comment by gh3597** [comment]
Yes that looks like it's working OK now @nicolasprigent. Thank you for that, much appreciated.

**Comment by nicolasprigent** [comment]
Perfect 👍
