### ISSUE TITLE
copy event for monospace text? 

### ISSUE THREAD

**Issue by DrKlipper** [nicolasprigent/Dokuwiki-Copycode-plugin#13]
Hi !
Very nice plugin for fast copy actions of code blocks. 

In my DW I use a lot of monosace formattings liek this: 
![grafik](https://github.com/nicolasprigent/Dokuwiki-Copycode-plugin/assets/119651689/46a85bf5-1092-4423-a8ba-53b070a2b15c)

Do you see a chance to have a second setting for enabling copy such elements? 
This would be a great addition since those monospace elements are often used for commands. 

Oh and one other question ... If I hover over a code block the icon changes to a bold + sign. 
Wouldn´t it be better to have another symbole? 
Maybe also configurable?

**Comment by DrKlipper** [comment]
Just comment my own question ... 
I realised that copiing monospace text is already working :-)
And furthermore ... Changing the cursor is only editing the style.css file. 
I choosed cursor:grabbing; 

This can be closed. 
Anyway. Thx for this awesome piece of code !!

**Comment by DrKlipper** [comment]
Solution already there :-)

**Comment by nicolasprigent** [comment]
hello @DrKlipper , I was starting to investigate, and I thought that you had some plugin replacing inline `<code>` tag that is generated with the markup you show on your screenshot with something like `<tt>` tag maybe or something even more exotic. So yes the inline copy of code is working. I'll maybe add an option in the configuration to choose the cursor in a list, because on next plugin update, it would be back to a cross. Good idea.

**Comment by DrKlipper** [comment]
Just as an update ... What I was talking about is the Monospaced Text: 
![grafik](https://github.com/nicolasprigent/Dokuwiki-Copycode-plugin/assets/119651689/cd36899f-f784-4ceb-8511-995c2b4fc499)
The markup which uses 2 of the single quotes on each side. 
But it´s working. So I´m totally fine right now. :-)

**Comment by nicolasprigent** [comment]
I've made an update for the cursor : you can now choose in the configuration the cursor that you want. You should see an update notice in the extension manager or else click on reinstall to get the last version of the plugin. Let me know what you think of it.
