### ISSUE TITLE
Add an option to disable auto-copy of highlighted text.

### ISSUE THREAD

**Issue by tvataire** [nicolasprigent/Dokuwiki-Copycode-plugin#15]
This would allow users to use features of the web browser's context menu when selecting a range of code.
Related PR : #14

**Comment by nicolasprigent** [comment]
hello @tvataire , that refactor on script.js is something, I'm not sure to understand the code anymore 😄 I review this and I'll merge it, no problem

**Comment by nicolasprigent** [comment]
Just to make no mistake, in wich order should I make the merges ? #14 then #16 ? I'm not that proficient with github merges, I'm sorry

**Comment by tvataire** [comment]
Hello
There's something strange in #16 : seems to include commits from #14 ...
Anyway merge #14 then #16 seems to be OK.

**Comment by nicolasprigent** [comment]
Yes that's what bugged me 😆 . I've made a review of your code, it's really more robust than my first dirty script was.

**Comment by tvataire** [comment]
Thanks for merging !
I close both #15 and #17.

**Comment by nicolasprigent** [comment]
Thanks for the work you put on it !
