### ISSUE TITLE
Not able to update on newest(today) Dokuwiki on apache2 php 7.3.19-1 from 2020-06-25 to 2020-07-01

### ISSUE THREAD

**Issue by raho0003** [nicolasprigent/Dokuwiki-Copycode-plugin#3]
![copycode](https://user-images.githubusercontent.com/47673359/91532127-24891900-e90e-11ea-9bc0-fb535818c678.PNG)

**Comment by nicolasprigent** [comment]
You should retry, I think it was because I haven't updated plugin.info.txt to last version date. Sorry for the inconvenience.

**Comment by raho0003** [comment]
Thank you
