### ISSUE TITLE
<file> </file> without name ... does not work

### ISSUE THREAD

**Issue by dryoo** [nicolasprigent/Dokuwiki-Copycode-plugin#4]
You did great job!

```
<code>
Works! :)
</code>

<code batch>
Works! :)
</code>

<file sdf.txt>
Works! :)
</file>

<file>
does not work :(
</file>

```

**Comment by nicolasprigent** [comment]
Nice find, strangely, dokuwiki doesn't add the .code class on \<file\> tag if it has no filename. I added pre.file on the jquery selectors, now it should work.
