### ISSUE TITLE
I cant get it work in the latest dokuwiki

### ISSUE THREAD

**Issue by mamekedi** [nicolasprigent/Dokuwiki-Copycode-plugin#5]
I can install the plugin succesfully in the latest dokuwiki i can see the cross when i hover over the codeblock but it wont copy i cant see the message copied

**Comment by nicolasprigent** [comment]
On my installation it still works. It looks like you don't have jquery available on your dokuwiki. Go to Admin panel, then config page. Look for jquery parameter and choose "Yes : CDN code.jquery.com"
Tell me if it works !

**Comment by mamekedi** [comment]
HI,

It’s on but it’s not working
(I use the bootstrap 3 theme)
[cid:image003.jpg@01D7052B.53FDE600]



[cid:image004.jpg@01D7052B.53FDE600]

**Comment by nicolasprigent** [comment]
Do you have any error in the javascript console of your browser ?

**Comment by mamekedi** [comment]
Hi , please see the attachment

**Comment by mamekedi** [comment]
Now I do get an error

**Comment by nicolasprigent** [comment]
Could you copy your error logs in the javascript console please ?
Does your url is secured (https) ?
what is you browser ?

**Comment by mamekedi** [comment]
HI,

1:


js.php?t=bootstrap3&…15b9312f5eb040386:1 Uncaught TypeError: Cannot read property 'writeText' of undefined at writeToClipboard (js.php?t=bootstrap3&…15b9312f5eb040386:1) at HTMLPreElement.<anonymous> (js.php?t=bootstrap3&…15b9312f5eb040386:1)
writeToClipboard
@
js.php?t=bootstrap3&…15b9312f5eb040386:1
(anonymous)
@
js.php?t=bootstrap3&…15b9312f5eb040386:1
3
js.php?t=bootstrap3&…15b9312f5eb040386:1 Uncaught TypeError: Cannot read property 'writeText' of undefined at writeToClipboard (js.php?t=bootstrap3&…15b9312f5eb040386:1) at HTMLPreElement.<anonymous> (js.php?t=bootstrap3&…15b9312f5eb040386:1)
4
js.php?t=bootstrap3&…15b9312f5eb040386:1 Uncaught TypeError: Cannot read property 'writeText' of undefined at writeToClipboard (js.php?t=bootstrap3&…15b9312f5eb040386:1) at HTMLPreElement.<anonymous> (js.php?t=bootstrap3&…15b9312f5eb040386:1)
3
js.php?t=bootstrap3&…15b9312f5eb040386:1 Uncaught TypeError: Cannot read property 'writeText' of undefined at writeToClipboard (js.php?t=bootstrap3&…15b9312f5eb040386:1) at HTMLPreElement.<anonymous> (js.php?t=bootstrap3&…15b9312f5eb040386:1)
writeToClipboard
@
js.php?t=bootstrap3&…15b9312f5eb040386:1
(anonymous)
@
js.php?t=bootstrap3&…15b9312f5eb040386:1
2
js.php?t=bootstrap3&…15b9312f5eb040386:1 Uncaught TypeError: Cannot read property 'writeText' of undefined at writeToClipboard (js.php?t=bootstrap3&…15b9312f5eb040386:1) at HTMLPreElement.<anonymous> (js.php?t=bootstrap3&…15b9312f5eb040386:1)
js.php?t=bootstrap3&…15b9312f5eb040386:1 Uncaught TypeError: Cannot read property 'writeText' of undefined at writeToClipboard (js.php?t=bootstrap3&…15b9312f5eb040386:1) at HTMLPreElement.<anonymous> (js.php?t=bootstrap3&…15b9312f5eb040386:1)
writeToClipboard
@
js.php?t=bootstrap3&…15b9312f5eb040386:1
(anonymous)
@
js.php?t=bootstrap3&…15b9312f5eb040386:1


2:
Im running a local dokuwiki on ipadress not dns
3:
Im running Chrome

**Comment by nicolasprigent** [comment]
Ok, the clipboard function of the browser seems to fail. Wich version of Chrome do you use ?
It should work on localhost, with chrome versions above 66, but I think that for security reasons, the dokuwiki should be on a secured address served with https. Have you tested on an other browser, like firefox ?

**Comment by mamekedi** [comment]
When i login on my work there is other dokuwiki with dns
If i make contant from my computer to that dokuwiki its working so the browser is oke

Met vriendelijke groeten,
Marty en Diana Janssen

________________________________

**Comment by nicolasprigent** [comment]
Only for testing, could you paste chrome://flags/ in your chrome browser. Then go to "Insecure origins treated as secure", enable it and test again.

**Comment by mamekedi** [comment]
Thank for your great support but its still not working

Met vriendelijke groeten,
Marty en Diana Janssen

________________________________

**Comment by nicolasprigent** [comment]
No problem, glad to help :+1: 
have you tried on another browser ?
You said that it works on an another installation that is hosted at your work ?

**Comment by mamekedi** [comment]
Yes i have tried another browser no success
_______________

You said that it works on an another installation that is hosted at your work ?

YES .... with DNS url ...... and i use chrome ...


Met vriendelijke groeten,
Marty en Diana Janssen

________________________________

**Comment by mamekedi** [comment]
Hi Nicolas,

I installed a new dokuwiki on my Synology NAS and I get the same error:

[cid:image002.jpg@01D70559.533EC5D0]

JQMIGRATE: Migrate is installed, version 3.0.0

js.php?t=dokuwiki&tseed=d8d2f8d29c7c75b52f523d6fb03f5cec:1 Uncaught TypeError: Cannot read property 'writeText' of undefined
    at writeToClipboard (js.php?t=dokuwiki&tseed=d8d2f8d29c7c75b52f523d6fb03f5cec:1)
    at HTMLPreElement.<anonymous> (js.php?t=dokuwiki&tseed=d8d2f8d29c7c75b52f523d6fb03f5cec:1)
writeToClipboard @ js.php?t=dokuwiki&tseed=d8d2f8d29c7c75b52f523d6fb03f5cec:1
(anonymous) @ js.php?t=dokuwiki&tseed=d8d2f8d29c7c75b52f523d6fb03f5cec:1


Best Regards
Marty en Diana Janssen

**Comment by mamekedi** [comment]
Hi Nicolas,

I also tried the following plugin and this one works

https://www.dokuwiki.org/plugin:codeclipboard

BUT I WANT YOURS TO WORK 😊

**Comment by nicolasprigent** [comment]
Yes it uses a different approach, I will try to mix mine and this one if mine fails.

**Comment by mamekedi** [comment]
OKe thank you

**Comment by nicolasprigent** [comment]
You can update the plugin, let me know if it works now

**Comment by mamekedi** [comment]
Hi Nicolas,

Perfect it works MANY MANY THANKS !!!!

Best Regards,
Marty

**Comment by nicolasprigent** [comment]
No problem ! If you want to help this plugin, you could do some translation. I only have English and French for now. So if you can translate this 3 lines of code (https://github.com/nicolasprigent/Dokuwiki-Copycode-plugin/blob/master/lang/en/lang.php) in another language, let me know.

**Comment by mamekedi** [comment]
Hi Nicolas,

I prefer English that’s what almost anyone can read , so that would be enough do you think ?

**Comment by nicolasprigent** [comment]
it's an automatic option, if the language of your installation is french for example, it's automatically translated. It's just to have more options.

**Comment by mamekedi** [comment]
Oke Nicolas,

For you 😊 in dutch

===========================================================================
In dutch:
===========================================================================

$lang['js']['Gekopieerd'] = 'De Code is gekopieerd!';
$lang['js']['selectiegekopieerd'] = 'De geselecteerde Code is gekopieerd!';
$lang['js']['Error'] = 'Er is iets fout gegaan met het kopiëren van de Code.';

===========================================================================

Best Regards,
Marty

**Comment by nicolasprigent** [comment]
thanks !
