### ISSUE TITLE
Allow copying of inline-code

### ISSUE THREAD

**Issue by FootStark** [nicolasprigent/Dokuwiki-Copycode-plugin#6]
Hi,

thanks for sharing your plugin.

Copycode works well on Code blocks, yet it does not with inline code.

Is there a special reason for this?

Inline code (marked via `''` in Dokuwiki) is simply translated to a HTML-`<code>`-Element, so a simple
`    var bloc_code = jQuery("pre.code, pre.file, code");`
should do the job...

I would really appreciate this extension, as our Wiki is filled with one-liners where inline-code is used.

Thanks.

**Comment by nicolasprigent** [comment]
Hi, there's absolutely no reason, I just haven't thinked of this :D
I tested right away and it works fine, I'll do the update in the next minutes.
Thanks for the suggestion !

**Comment by nicolasprigent** [comment]
You can update the plugin on your install. If you find anything that is not working as expected, let me know.

**Comment by FootStark** [comment]
Wow, thanks for quick resonse! I also hab a go at it and implemented it via an option (settable on Config-page). I submitted it as a pull request. Maybe it's not a 100% necessary, but it also provides the structure to implement further options in the future...

**Comment by nicolasprigent** [comment]
Thanks FootStark, I'll check your code and merge it, I think it's a great idea to have some options. I close this issue.
