### ISSUE TITLE
Cant update -  think I can, but version number may have not been upped.

### ISSUE THREAD

**Issue by raho0003** [nicolasprigent/Dokuwiki-Copycode-plugin#9]
![Screenshot_2021-05-28 Erweiterungen verwalten  TZE-Wiki](https://user-images.githubusercontent.com/47673359/119952181-0768a000-bf9d-11eb-9486-5d856356d768.png)

**Comment by nicolasprigent** [comment]
Sorry for that, I forgot to update plugin.info.txt. Can you try to update, see if it works now ?

**Comment by raho0003** [comment]
Works! Thanks!
